"""initial schema

Revision ID: 3e668c4b0094
Revises:
Create Date: 2026-07-30 16:53:49.541809
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

import agentskills_hub_core.types

revision: str = "3e668c4b0094"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("created_at", agentskills_hub_core.types.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("team", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_team_slug"), ["slug"], unique=True)

    op.create_table(
        "environment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("created_at", agentskills_hub_core.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "name", name="uq_environment_team_name"),
    )
    with op.batch_alter_table("environment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_environment_team_id"), ["team_id"], unique=False)

    op.create_table(
        "skill",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "scope",
            sa.Enum("org", "domain", "team", name="skill_scope", native_enum=False),
            nullable=False,
        ),
        sa.Column("owner_team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("listed", "unlisted", name="visibility", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "subscription_model",
            sa.Enum("open", "approval-required", name="subscription_model", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "lifecycle",
            sa.Enum("active", "deprecated", "archived", name="skill_lifecycle", native_enum=False),
            nullable=False,
        ),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_at", agentskills_hub_core.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "scope", "owner_team_id", name="uq_skill_identity"),
    )
    with op.batch_alter_table("skill", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skill_owner_team_id"), ["owner_team_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_skill_skill_id"), ["skill_id"], unique=False)

    op.create_table(
        "api_key",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("prefix", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("key_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("created_at", agentskills_hub_core.types.UtcDateTime(), nullable=False),
        sa.Column("last_used_at", agentskills_hub_core.types.UtcDateTime(), nullable=True),
        sa.Column("revoked_at", agentskills_hub_core.types.UtcDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_api_key_environment_id"), ["environment_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_api_key_prefix"), ["prefix"], unique=True)
        batch_op.create_index(batch_op.f("ix_api_key_team_id"), ["team_id"], unique=False)

    op.create_table(
        "skill_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
        sa.Column("content_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("catalog_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "review",
                "published",
                "deprecated",
                "archived",
                name="version_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("published_at", agentskills_hub_core.types.UtcDateTime(), nullable=True),
        sa.Column("published_by", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "version", name="uq_skill_version"),
    )
    with op.batch_alter_table("skill_version", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skill_version_skill_id"), ["skill_id"], unique=False)

    op.create_table(
        "subscription",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "origin",
            sa.Enum(
                "manual", "collection", "policy", name="subscription_origin", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "pending-approval",
                "revoked",
                name="subscription_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", agentskills_hub_core.types.UtcDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("environment_id", "skill_id", name="uq_subscription_environment_skill"),
    )
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subscription_environment_id"), ["environment_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_subscription_skill_id"), ["skill_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_subscription_team_id"), ["team_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscription_team_id"))
        batch_op.drop_index(batch_op.f("ix_subscription_skill_id"))
        batch_op.drop_index(batch_op.f("ix_subscription_environment_id"))

    op.drop_table("subscription")
    with op.batch_alter_table("skill_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_version_skill_id"))

    op.drop_table("skill_version")
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_key_team_id"))
        batch_op.drop_index(batch_op.f("ix_api_key_prefix"))
        batch_op.drop_index(batch_op.f("ix_api_key_environment_id"))

    op.drop_table("api_key")
    with op.batch_alter_table("skill", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_skill_id"))
        batch_op.drop_index(batch_op.f("ix_skill_owner_team_id"))

    op.drop_table("skill")
    with op.batch_alter_table("environment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_environment_team_id"))

    op.drop_table("environment")
    with op.batch_alter_table("team", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_slug"))

    op.drop_table("team")
    # ### end Alembic commands ###
